name: mockalization_example
description: "Mockalization usage example"
publish_to: 'none'
version: 0.1.0

resolution: workspace

environment:
  sdk: '^3.6.0'

dependencies:
  mockalization_factory:
    path: ../mockalization_factory/

dev_dependencies:
  build_runner: ^2.4.11
  mockalization_generator:
    path: ../mockalization_generator/
