name: mockalization
description: "Annotation-based mock data generator for Dart"
version: 2.0.2
publish_to: 'none'

environment:
  sdk: '^3.7.0'

workspace:
  - example
  - mockalization_factory
  - mockalization_generator

dev_dependencies:
  lints: ^5.1.1
