name: mockalization_generator
description: "Code generator for mockalization - generates mock data factory extensions"
version: 2.0.0

resolution: workspace

environment:
  sdk: '^3.6.0'

dependencies:
  build: ^2.4.1
  source_gen: ^1.5.0
  analyzer: ^6.4.1
  mockalization_factory:
    path: ../mockalization_factory/
