name: mockalization_factory
description: "Annotations and types for the mockalization mock data code generator"
version: 2.0.0

resolution: workspace

environment:
  sdk: '^3.6.0'

dependencies:
  faker: ^2.2.0
  uuid: ^4.5.1
